FROM node:22-alpine

WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli@19

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

EXPOSE 4210

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4210", "--poll", "2000"]

