// # AUTO-GENERATED by generate-env.sh — DO NOT EDIT MANUALLY
export const environment = {
  production: false,
  apiUrl: 'http://localhost:8010',
  supersetUrl: 'http://localhost:8088',
  environment: 'local',
};
