#!/usr/bin/env bash
# ============================================================
# generate-env.sh — Generate component .env files from root config
# Usage: ./scripts/generate-env.sh local|dev|test
# ============================================================
set -euo pipefail

HEADER="# AUTO-GENERATED by generate-env.sh — DO NOT EDIT MANUALLY"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Argument validation ─────────────────────────────────────
ENV="${1:-}"
if [[ -z "$ENV" ]]; then
  echo "❌ Usage: $0 local|dev|test"
  exit 1
fi

case "$ENV" in
  local|dev|test) ;;
  prod)
    echo "❌ Production environment is not supported by this script."
    exit 1
    ;;
  *)
    echo "❌ Unknown environment: $ENV (expected: local, dev, test)"
    exit 1
    ;;
esac

# ── Load source .env ────────────────────────────────────────
if [[ "$ENV" == "local" ]]; then
  SOURCE_FILE="$REPO_ROOT/.env"
else
  SOURCE_FILE="$REPO_ROOT/.env.$ENV"
fi

if [[ ! -f "$SOURCE_FILE" ]]; then
  echo "❌ Source file not found: $SOURCE_FILE"
  exit 1
fi

# Source the env file (handle quoted values)
set -a
# shellcheck disable=SC1090
source "$SOURCE_FILE"
set +a
echo "📁 Loaded: $SOURCE_FILE"

# ── Helper: write a var ─────────────────────────────────────
write_var() {
  local var_name="$1"
  local value="${!var_name:-}"
  echo "${var_name}=${value}"
}

# ── 1. backend/.env ─────────────────────────────────────────
BACKEND_ENV="$REPO_ROOT/backend/.env"

if [[ "$ENV" == "local" ]]; then
  BACKEND_SUPERSET_URL="http://rcq_superset:8088"
  BACKEND_FRONTEND_URL="http://localhost:4210"
else
  BACKEND_SUPERSET_URL="${SUPERSET_URL:-}"
  BACKEND_FRONTEND_URL="${CORS_ORIGINS%%,*}"
fi

cat > "$BACKEND_ENV" <<EOF
$HEADER
$(write_var ENVIRONMENT)
$(write_var RCQ_DB_HOST)
$(write_var RCQ_DB_PORT)
$(write_var RCQ_DB_NAME)
$(write_var RCQ_DB_USER)
$(write_var RCQ_DB_PASSWORD)
$(write_var GOOGLE_OAUTH_CLIENT_ID)
$(write_var GOOGLE_OAUTH_CLIENT_SECRET)
$(write_var GOOGLE_REDIRECT_URI)
$(write_var JWT_SECRET_KEY)
SUPERSET_URL=${BACKEND_SUPERSET_URL}
$(write_var SUPERSET_ADMIN_USERNAME)
$(write_var SUPERSET_ADMIN_PASSWORD)
$(write_var SUPERSET_DASHBOARD_YEARLY_GOAL)
$(write_var CORS_ORIGINS)
FRONTEND_URL=${BACKEND_FRONTEND_URL}
$(write_var DEBUG)
EOF
echo "✅ Generated: $BACKEND_ENV"

# ── 2. superset/.env ────────────────────────────────────────
SUPERSET_ENV="$REPO_ROOT/superset/.env"

cat > "$SUPERSET_ENV" <<EOF
$HEADER
$(write_var MYSQL_ROOT_PASSWORD)
$(write_var MYSQL_DATABASE)
$(write_var MYSQL_USER)
$(write_var MYSQL_PASSWORD)
$(write_var SUPERSET_SECRET_KEY)
$(write_var SUPERSET_ADMIN_USERNAME)
$(write_var SUPERSET_ADMIN_PASSWORD)
$(write_var SUPERSET_ADMIN_EMAIL)
$(write_var SUPERSET_ADMIN_FIRST_NAME)
$(write_var SUPERSET_ADMIN_LAST_NAME)
SUPERSET_METADATA_DB_USER=${SUPERSET_DB_RW_USER:-}
SUPERSET_METADATA_DB_PASS=${SUPERSET_DB_RW_PASSWORD:-}
$(write_var SUPERSET_CORS_ORIGINS)
$(write_var VALKEY_HOST)
$(write_var VALKEY_PORT)
$(write_var VALKEY_DB)
EOF
echo "✅ Generated: $SUPERSET_ENV"

# ── 3. superset/provisioning/.env.{env} ─────────────────────
PROV_ENV="$REPO_ROOT/superset/provisioning/.env.$ENV"

if [[ "$ENV" == "local" ]]; then
  PROV_SUPERSET_URL="http://localhost:8088"
  # Superset runs inside Docker — use Docker-internal hostname for MySQL
  PROV_DB_SQLALCHEMY_URI="mysql+mysqldb://${MYSQL_USER:-rcq_readonly}:${MYSQL_PASSWORD:-rcq_password}@rcq_mysql:3306/${MYSQL_DATABASE:-rcq_fr_dev_db}"
  PROV_EMBEDDING_ALLOWED_DOMAINS="http://localhost:4210"
else
  PROV_SUPERSET_URL="${SUPERSET_URL:-}"
  PROV_DB_SQLALCHEMY_URI="${DB_SQLALCHEMY_URI:-}"
  PROV_EMBEDDING_ALLOWED_DOMAINS="${EMBEDDING_ALLOWED_DOMAINS:-}"
fi

cat > "$PROV_ENV" <<EOF
$HEADER
SUPERSET_URL=${PROV_SUPERSET_URL}
SUPERSET_ADMIN_USER=${SUPERSET_ADMIN_USERNAME:-admin}
SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD:-}
DB_CONNECTION_NAME=${DB_CONNECTION_NAME:-RCQ MySQL}
DB_SQLALCHEMY_URI=${PROV_DB_SQLALCHEMY_URI}
EMBEDDING_ALLOWED_DOMAINS=${PROV_EMBEDDING_ALLOWED_DOMAINS}
BACKEND_ENV_PATH=../../backend/.env
EOF
echo "✅ Generated: $PROV_ENV"

# ── 4. frontend environment (local only) ────────────────────
if [[ "$ENV" == "local" ]]; then
  FRONTEND_ENV="$REPO_ROOT/frontend/src/environments/environment.local.ts"
  cat > "$FRONTEND_ENV" <<EOF
// $HEADER
export const environment = {
  production: false,
  apiUrl: 'http://localhost:8010',
  supersetUrl: 'http://localhost:8088',
  environment: 'local',
};
EOF
  echo "✅ Generated: $FRONTEND_ENV"
fi

echo ""
echo "🎉 All .env files generated for environment: $ENV"
